version: "3.3"
services:
  # MongoDB para Timber
  timber-mongo:
    image: mongo:6.0
    container_name: timber-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: merkle_tree
    volumes:
      - timber-mongo-data:/data/db
    networks:
      - starlight
    ports:
      - "27017:27017"

  # MongoDB para ZApp
  zapp-mongo:
    image: mongo:6.0
    container_name: zapp-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: zapp_db
    volumes:
      - zapp-mongo-data:/data/db
    networks:
      - starlight
    ports:
      - "27018:27017"

  # Zokrates Worker (imagem pública)
  zokrates:
    image: ghcr.io/eyblockchain/zokrates-worker-updated:latest
    container_name: zokrates
    restart: unless-stopped
    volumes:
      - ./proving-files:/app/output
      - ./circuits:/app/circuits
      - ./orchestration/common/write-vk.mjs:/app/write-vk.mjs
      - ./orchestration/common/db:/app/orchestration/common/db
    networks:
      - starlight
    ports:
      - "8080:8080"

  # Timber Service (usando Node.js público)
  timber:
    image: node:18-alpine
    container_name: timber
    restart: unless-stopped
    working_dir: /app
    environment:
      - RPC_URL=ws://host.docker.internal:8545
      - LOG_LEVEL=debug
      - DB_URL=mongodb://admin:admin@timber-mongo:27017
      - HASH_TYPE=mimc
      - UNIQUE_LEAVES=true
      - ESCROW_SHIELD_ADDRESS=0xf3cBfC5c2d71CdB931B004b3B5Ca4ABEdbA3Cd43
    volumes:
      - ./build/contracts:/app/build/contracts
      - ./config_timber.js:/app/config/default.js
      - ./timber-package.json:/app/package.json
    networks:
      - starlight
    ports:
      - "3100:80"
    depends_on:
      - timber-mongo
    command: >
      sh -c "
        npm install &&
        npm start
      "

  # ZApp Service (usando Node.js público)
  zapp:
    image: node:18-alpine
    container_name: zapp
    restart: unless-stopped
    working_dir: /app
    environment:
      - ESCROW_SHIELD_ADDRESS=0xf3cBfC5c2d71CdB931B004b3B5Ca4ABEdbA3Cd43
      - ERC20_ADDRESS=0x3A34C530700E3835794eaE04d2a4F22Ce750eF7e
      - ZOKRATES_URL=http://zokrates:8080
      - TIMBER_URL=http://timber:80
      - RPC_URL=ws://host.docker.internal:8545
      - DEFAULT_ACCOUNT=0x0000000000000000000000000000000000000000
      - KEY=0x0000000000000000000000000000000000000000000000000000000000000000
      - ADMIN_ACCOUNT=0x0000000000000000000000000000000000000000
      - ADMIN_KEY=0x0000000000000000000000000000000000000000000000000000000000000000
      - MONGO_URL=mongodb://admin:admin@zapp-mongo:27017
    volumes:
      - ./db:/app/orchestration/common/db
      - ./zapp-package.json:/app/package.json
    networks:
      - starlight
    ports:
      - "3000:3000"
    depends_on:
      - timber
      - zapp-mongo
      - zokrates
    command: >
      sh -c "
        npm install &&
        npm start
      "

networks:
  starlight:
    driver: bridge

volumes:
  timber-mongo-data:
  zapp-mongo-data: