services:
  # MongoDB para os serviços
  mongodb:
    image: mongo:6.0
    container_name: cbd-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: cbd_db
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

  # Zokrates Worker (imagem pública)
  zokrates:
    image: ghcr.io/eyblockchain/zokrates-worker-updated:latest
    container_name: cbd-zokrates
    restart: unless-stopped
    volumes:
      - ./proving-files:/app/output
      - ./circuits:/app/circuits
    ports:
      - "8080:8080"

  # Serviço Timber (Node.js)
  timber:
    image: node:18-alpine
    container_name: cbd-timber
    restart: unless-stopped
    working_dir: /app
    environment:
      - RPC_URL=ws://host.docker.internal:8545
      - LOG_LEVEL=debug
      - DB_URL=mongodb://admin:admin@mongodb:27017
      - HASH_TYPE=mimc
      - UNIQUE_LEAVES=true
      - ESCROW_SHIELD_ADDRESS=0xf3cBfC5c2d71CdB931B004b3B5Ca4ABEdbA3Cd43
    volumes:
      - ./build/contracts:/app/build/contracts
      - ./config_timber.js:/app/config/default.js
      - ./timber-package.json:/app/package.json
      - ./timber-index.js:/app/index.js
    ports:
      - "3100:80"
    depends_on:
      - mongodb
    command: >
      sh -c "
        npm install &&
        echo 'Timber service starting...' &&
        sleep 10 &&
        npm start
      "

  # Serviço ZApp (Node.js)
  zapp:
    image: node:18-alpine
    container_name: cbd-zapp
    restart: unless-stopped
    working_dir: /app
    environment:
      - ESCROW_SHIELD_ADDRESS=0xf3cBfC5c2d71CdB931B004b3B5Ca4ABEdbA3Cd43
      - ERC20_ADDRESS=0x3A34C530700E3835794eaE04d2a4F22Ce750eF7e
      - ZOKRATES_URL=http://zokrates:8080
      - TIMBER_URL=http://timber:80
      - RPC_URL=ws://host.docker.internal:8545
      - DEFAULT_ACCOUNT=0x0000000000000000000000000000000000000000
      - KEY=0x0000000000000000000000000000000000000000000000000000000000000000
      - ADMIN_ACCOUNT=0x0000000000000000000000000000000000000000
      - ADMIN_KEY=0x0000000000000000000000000000000000000000000000000000000000000000
      - MONGO_URL=mongodb://admin:admin@mongodb:27017
    volumes:
      - ./db:/app/orchestration/common/db
      - ./zapp-package.json:/app/package.json
      - ./zapp-index.js:/app/index.js
    ports:
      - "3000:3000"
    depends_on:
      - timber
      - mongodb
      - zokrates
    command: >
      sh -c "
        npm install &&
        echo 'ZApp service starting...' &&
        sleep 10 &&
        npm start
      "

  # Frontend Web (Nginx)
  frontend:
    image: nginx:alpine
    container_name: cbd-frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - zapp
      - timber

networks:
  default:
    driver: bridge

volumes:
  mongodb-data: 